Websites/CMSSolutions.Websites/Controllers/HomeVipXuController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using CMSSolutions.ContentManagement.Widgets.Services;
using CMSSolutions.DisplayManagement;
using CMSSolutions.Extensions;
using CMSSolutions.Web.Mvc;
using CMSSolutions.Web.Themes;
using CMSSolutions.Websites.Entities;
using CMSSolutions.Websites.Extensions;
using CMSSolutions.Websites.Models;
using CMSSolutions.Websites.Payments;
using CMSSolutions.Websites.Services;
using CMSSolutions.Websites.VipHDBankCardServices;

namespace CMSSolutions.Websites.Controllers
{
    [Themed(IsDashboard = false)]
    public class HomeVipXuController : BaseHomeController
    {
        private readonly dynamic shapeFactory;
        public HomeVipXuController(IWorkContextAccessor workContextAccessor, IShapeFactory shapeFactory) 
            : base(workContextAccessor)
        {
            this.shapeFactory = shapeFactory;
        }

        [Url("tai-tro.html")]
        public ActionResult Index()
        {
            UrlLogin = Request.Url != null ? Request.Url.AbsoluteUri : Url.Action("Index", "Home");
            var model = new PaymentModel();
            model.PageName = 1;
            if (!IsLogin)
            {
                return Redirect(Url.Action("Index", "Home"));
            }

            var customerService = WorkContext.Resolve<ICustomerService>();
            CustomerInfo customer = customerService.GetCustomerByCacheId(UserId);
            SetCustomerState(customer);

            #region Payments
            var transid = Request.QueryString["?transid"];
            var responCode = Request.QueryString["responCode"];
            var mac = Request.QueryString["mac"];
            var amount = Request.QueryString["amount"];
            var bankCode = Request.QueryString["bankCode"];

            var encrypter = new DesSecurity();
            var apiBank = new APIBankCardService();
            var transactionBankService = WorkContext.Resolve<ITransactionBankService>();
            var serviceLog = new APISmsService();
            if (mac != encrypter.DESMAC(transid + responCode, apiBank.ReceiverKey) && !String.IsNullOrEmpty(transid))
            {
                model.Messages = "Giao dịch nạp VIPXU qua thẻ ngân hàng thất bại.";
                model.Status = false;
                model.Url = "";
                var transaction = new TransactionBankInfo
                {
                    CustomerCode = CustomerCode,
                    TransactionCode = TransactionCode,
                    CreateDate = DateTime.Now,
                    BankCode = bankCode,
                    Amount = amount,
                    ResponCode = responCode,
                    Mac = mac,
                    TransId = transid,
                    Type = (int)TransferType.Rereceive,
                    Description = "Giao dịch nạp VIPXU qua thẻ ngân hàng thất bại.",
                    Status = (int)PaymentStatus.Close
                };

                transactionBankService.BankProcessing(transaction, 0);
                serviceLog.InsertLog(new LogInfo
                {
                    CreateDate = DateTime.Now,
                    Messages = "Giao dịch nạp VIPXU qua thẻ ngân hàng thất bại.",
                    Keyword = bankCode,
                    Contents = "Mã GD: " + TransactionCode + " - Mã KH: " + CustomerCode + " - Số tiền nạp: " + amount,
                    Type = (int)LogType.BankCard,
                    Status = (int)LogStatus.Error
                });
                TransactionCode = null;
            }

            if (!string.IsNullOrEmpty(transid) && !string.IsNullOrEmpty(responCode) && Convert.ToInt32(responCode) != (int)BankErrorMessages.Success)
            {
                model.Messages = "Giao dịch nạp VIPXU qua thẻ ngân hàng thất bại.";
                model.Status = false;
                model.Url = "";
                var transaction = new TransactionBankInfo
                {
                    CustomerCode = CustomerCode,
                    TransactionCode = TransactionCode,
                    CreateDate = DateTime.Now,
                    BankCode = bankCode,
                    Amount = amount,
                    ResponCode = responCode,
                    Mac = mac,
                    TransId = transid,
                    Type = (int)TransferType.Rereceive,
                    Description = "Giao dịch thất bại",
                    Status = (int)PaymentStatus.Close
                };

                transactionBankService.BankProcessing(transaction, 0);
                serviceLog.InsertLog(new LogInfo
                {
                    CreateDate = DateTime.Now,
                    Messages = "Giao dịch nạp VIPXU qua thẻ ngân hàng thất bại.",
                    Keyword = bankCode,
                    Contents = TransactionCode + " " + CustomerCode + " " + amount,
                    Type = (int)LogType.BankCard,
                    Status = (int)LogStatus.Error
                });

                TransactionCode = null;
            }

            if (!string.IsNullOrEmpty(TransactionCode) && !string.IsNullOrEmpty(transid) && Convert.ToInt32(responCode) == (int)BankErrorMessages.Success)
            {
                var vipXu = TotalVipXu(int.Parse(amount));
                model.Messages = string.Format("Bạn đã nạp {0} VIPXU vào tài khoản {1} thành công.", vipXu, CustomerCode);
                model.Status = true;
                model.Amount = amount;
                model.Url = string.Format("http://{0}", Extensions.Constants.HomeDomainName);

                var transaction = new TransactionBankInfo
                {
                    CustomerCode = CustomerCode,
                    TransactionCode = TransactionCode,
                    CreateDate = DateTime.Now,
                    BankCode = bankCode,
                    Amount = amount,
                    ResponCode = responCode,
                    Mac = mac,
                    TransId = transid,
                    Type = (int)TransferType.Rereceive,
                    Description = string.Format("Đã nạp {0} VIPXU vào tài khoản {1} thành công.", vipXu, CustomerCode),
                    Status = (int)PaymentStatus.Close
                };

                transactionBankService.BankProcessing(transaction, vipXu);
                serviceLog.InsertLog(new LogInfo
                {
                    CreateDate = DateTime.Now,
                    Messages = "Giao dịch nạp VIPXU qua thẻ ngân hàng thành công.",
                    Keyword = bankCode,
                    Contents = TransactionCode + " " + CustomerCode + " " + amount,
                    Type = (int)LogType.BankCard,
                    Status = (int)LogStatus.Success
                });

                TransactionCode = null;
                customerService.ResetCacheCustomers();
                customer = customerService.GetCustomerByCacheId(UserId);
                SetCustomerState(customer);
            }

            #endregion

            #region Init
            var serviceCategory = WorkContext.Resolve<ICategoryService>();
            serviceCategory.LanguageCode = WorkContext.CurrentCulture;

            SiteId = (int)Site.Home;
            serviceCategory.SiteId = SiteId;
            var cate = serviceCategory.GetByIdCache((int)FixCategories.NapVIP);
            ViewData[Extensions.Constants.HeaderTitle] = cate.Name;
            ViewData[Extensions.Constants.HeaderDescription] = cate.Description;
            ViewData[Extensions.Constants.HeaderKeywords] = cate.Tags;

            BindVipModules();

            var serviceBankCard = WorkContext.Resolve<IBankCardService>();
            model.ListBankCards = serviceBankCard.GetRecords(x => x.Status == (int)Status.Approved).ToList();
            var serviceCard = WorkContext.Resolve<ICardTypeService>();
            model.ListCardTypes = serviceCard.GetRecords(x => x.Status == (int)Status.Approved).ToList();
            model.CustomerCode = CustomerCode;
            #endregion

            return View(model);
        }

        [Url("tai-tro/0/thong-tin.html")]
        public ActionResult VipXuInfo()
        {
            UrlLogin = Request.Url != null ? Request.Url.AbsoluteUri : Url.Action("Index", "Home");
            var model = new PaymentModel();
            model.PageName = 0;
            model.CustomerName = FullName;
            model.VipXu = VipXu.ToString();
            if (!IsLogin)
            {
                model.Messages = "Bạn chưa đăng nhập.";
                model.Status = false;
                return Redirect(Url.Action("Index", "Home"));
            }

            #region Init
            var serviceCategory = WorkContext.Resolve<ICategoryService>();
            serviceCategory.LanguageCode = WorkContext.CurrentCulture;

            SiteId = (int)Site.Home;
            serviceCategory.SiteId = SiteId;
            var cate = serviceCategory.GetByIdCache((int)FixCategories.NapVIP);
            ViewData[Extensions.Constants.HeaderTitle] = cate.Name;
            ViewData[Extensions.Constants.HeaderDescription] = cate.Description;
            ViewData[Extensions.Constants.HeaderKeywords] = cate.Tags;

            BindVipModules();

            model.CustomerCode = CustomerCode;
            #endregion

            return View(model);
        }

        [Url("tai-tro/2/log-doi-xu.html")]
        public ActionResult LogDoiXu()
        {
            UrlLogin = Request.Url != null ? Request.Url.AbsoluteUri : Url.Action("Index", "Home");
            var model = new PaymentModel();
            model.PageName = 2;
            if (!IsLogin)
            {
                model.Messages = "Bạn chưa đăng nhập.";
                model.Status = false;
                return Redirect(Url.Action("Index", "Home"));
            }

            #region Init
            var serviceCategory = WorkContext.Resolve<ICategoryService>();
            serviceCategory.LanguageCode = WorkContext.CurrentCulture;

Websites/CMSSolutions.Websites/Views/HomeVipXu/LogDoiXu.cshtml
@model CMSSolutions.Websites.Models.PaymentModel
<div class="profi-cat-left">
    <ul class="profi-menu">
        <li>
            <a href="@Url.Action("VipXuInfo", "HomeVipXu")" class="@(Model.PageName == 0 ? "active" : string.Empty)">THÔNG TIN</a>
        </li>
        <li>
            <a href="@Url.Action("Index", "HomeVipXu")" class="@(Model.PageName == 1 ? "active" : string.Empty)">Nạp VIP!</a>
        </li>
        <li>
            <a href="@Url.Action("LogDoiXu", "HomeVipXu")" class="@(Model.PageName == 2 ? "active" : string.Empty)">Log đổi xu</a>
        </li>
        <li>
            <a href="@Url.Action("LogNapVip", "HomeVipXu")" class="@(Model.PageName == 3 ? "active" : string.Empty)">Log nạp VIP</a>
        </li>
    </ul>  

    <div id="page_index">
        <br class="clear_both">  
        <div class="log-pur-inf" style="margin-right: 20px;">
            <table width="100%" cellspacing="0" cellpadding="0" border="0">
                <tbody>
                    <tr>
                        <th scope="col">THỜI GIAN</th>
                        <th scope="col">SỐ TIỀN(VNĐ)</th>
                        <th scope="col">HÌNH THỨC NẠP</th>
                        <th scope="col">THAM CHIẾU</th>
                    </tr>
                    @if (Model.CustomerDoiXuHistories != null && Model.CustomerDoiXuHistories.Count > 0)
                    {
                        foreach (var item in Model.CustomerDoiXuHistories)
                        {
                            <tr>
                                <td>
                                    @item.CreateDate.ToString(CMSSolutions.Websites.Extensions.Constants.DateTimeFomatFull)
                                </td>
                                <td>
                                    @item.Amount
                                </td>
                                <td>
                                    @item.Type
                                </td>
                                <td>
                                    @item.TransactionCode
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td style="text-align: center" colspan="4">Không có dữ liệu</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>  

<script type="text/javascript">
    $(document).ready(function () {
        var customerCode = '@Model.CustomerCode';
        if (customerCode == '' || customerCode == null) {
            dialogBox('#loginBox');
        }
    });  
</script> 

Websites/CMSSolutions.Websites/Views/HomeVipXu/LogNapVip.cshtml
@model CMSSolutions.Websites.Models.PaymentModel
<div class="profi-cat-left">
    <ul class="profi-menu">
        <li>
            <a href="@Url.Action("VipXuInfo", "HomeVipXu")" class="@(Model.PageName == 0 ? "active" : string.Empty)">THÔNG TIN</a>
        </li>
        <li>
            <a href="@Url.Action("Index", "HomeVipXu")" class="@(Model.PageName == 1 ? "active" : string.Empty)">Nạp VIP!</a>
        </li>
        <li>
            <a href="@Url.Action("LogDoiXu", "HomeVipXu")" class="@(Model.PageName == 2 ? "active" : string.Empty)">Log đổi xu</a>
        </li>
        <li>
            <a href="@Url.Action("LogNapVip", "HomeVipXu")" class="@(Model.PageName == 3 ? "active" : string.Empty)">Log nạp VIP</a>
        </li>
    </ul>   

    <div id="page_index">
        <br class="clear_both">            
        <div class="log-pur-inf" style="margin-right: 20px;">
            <table id="store_history" width="100%" cellspacing="0" cellpadding="0" border="0">
                <tbody>
                    <tr>
                        <th scope="col">CÁC GÓI</th>
                        <th scope="col">GIÁ(VIPXU)</th>
                        <th scope="col">HẠN</th>
                        <th scope="col">THỜI GIAN</th>
                    </tr>
                    @if (Model.CustomerNapVipHistories != null && Model.CustomerNapVipHistories.Count > 0)
                    {
                        foreach (var item in Model.CustomerNapVipHistories)
                        {
                            <tr>
                                <td>
                                    @item.Package
                                </td>
                                <td>
                                    @item.Amount
                                </td>
                                <td>
                                    @(item.TextStartDate + " - " + @item.TextEndDate)
                                </td>
                                <td>
                                    @item.TotalDay
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td style="text-align: center" colspan="4">Không có dữ liệu</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>  

<script type="text/javascript">
    $(document).ready(function () {
        var customerCode = '@Model.CustomerCode';
        if (customerCode == '' || customerCode == null) {
            dialogBox('#loginBox');
        }
    });  
</script> 

Websites/CMSSolutions.Websites/Views/HomeVipXu/VipXuInfo.cshtml
@model CMSSolutions.Websites.Models.PaymentModel
<div class="profi-cat-left">
    <ul class="profi-menu">
        <li>
            <a href="@Url.Action("VipXuInfo", "HomeVipXu")" class="@(Model.PageName == 0 ? "active" : string.Empty)">THÔNG TIN</a>
        </li>
        <li>
            <a href="@Url.Action("Index", "HomeVipXu")" class="@(Model.PageName == 1 ? "active" : string.Empty)">Nạp VIP!</a>
        </li>
        <li>
            <a href="@Url.Action("LogDoiXu", "HomeVipXu")" class="@(Model.PageName == 2 ? "active" : string.Empty)">Log đổi xu</a>
        </li>
        <li>
            <a href="@Url.Action("LogNapVip", "HomeVipXu")" class="@(Model.PageName == 3 ? "active" : string.Empty)">Log nạp VIP</a>
        </li>
    </ul>   

    <div id="page_index">  
        <div class="mh-content-prod-text mh-donate-page">  
            <p style="line-height:20px;color:#333;margin-top:10px;">
                Chào <strong class="orange_color">@Model.CustomerName</strong> ! Mã số tài khoản của bạn là <strong class="orange_color">@Model.CustomerCode</strong>
            </p>
            <p>Bạn hiện có <strong class="orange_color">@Model.VipXu</strong> VipXu trong tài khoản. <br></p>
            <div class="log-pur-group">
                <div class="mh-pur-in2">
                    <div class="mh-content-prod-text">
                        <img style="width: 100%;" src="/Images/themes/so_sanh_VIP_thuong.jpg" />
                    </div>
                </div>
            </div> 
        </div>
    </div>
</div>  

<script type="text/javascript">
    $(document).ready(function () {
        var customerCode = '@Model.CustomerCode';
        if (customerCode == '' || customerCode == null) {
            dialogBox('#loginBox');
        }
    });  
</script> 